# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# aaaaawhich you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# aaaaaayou will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: vebsite
email: mike@veb.co.nz
description: >- # this means to ignore newlines until "baseurl:"
  Powered by the vebserwer beta 0.1
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://veb.co.nz" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: vebbed
github_username:  veb
linkedin_username: vebbed
pixelfed_username: mike

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: html
    css_class   : 'syntax'
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme
  - jemoji
  - jekyll-gist
  - jekyll-inline-svg
  - jekyll-include-cache

sass:
  style: compact

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
